# -*- coding: utf-8 -*-
"""FERRY,EFFICIENCY.ANALYTICS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0Yj59fpIXNp6vanTCatV4z85-qBjZIC
"""

# CELL 1 — LIBRARIES




import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

from sklearn.preprocessing import MinMaxScaler



import warnings
warnings.filterwarnings("ignore")

pd.set_option("st.write.max_columns", None)
pd.set_option("st.write.float_format", lambda x: f"{x:,.2f}")

print("All libraries loaded successfully.")

# CELL 2 — UPLOAD DATASET
import streamlit as st
import pandas as pd
import numpy as np

df = pd.read_csv("Toronto Island Ferry Tickets.csv")
                



print("Dataset shape:", df.shape)

print("\nColumns:")
for column in df.columns:
    print("-", column)

print("\nFirst 5 records:")
st.dataframe(df.head())

print("\nDataset information:")
df.info()

# CELL 4 — DATA QUALITY AUDIT


# Standardize column names
df.columns = df.columns.str.strip()

required_columns = [
    "_id",
    "Timestamp",
    "Sales Count",
    "Redemption Count"
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

# Convert timestamp
df["Timestamp"] = pd.to_datetime(
    df["Timestamp"],
    errors="coerce"
)

# Convert numerical columns
df["Sales Count"] = pd.to_numeric(
    df["Sales Count"],
    errors="coerce"
)

df["Redemption Count"] = pd.to_numeric(
    df["Redemption Count"],
    errors="coerce"
)

print("Missing values:")
st.write(df.isnull().sum())

print("\nDuplicate complete rows:", df.duplicated().sum())

print(
    "\nDuplicate _id values:",
    df["_id"].duplicated().sum()
)

print(
    "\nInvalid timestamps:",
    df["Timestamp"].isna().sum()
)

print(
    "\nNegative Sales Count:",
    (df["Sales Count"] < 0).sum()
)

print(
    "Negative Redemption Count:",
    (df["Redemption Count"] < 0).sum()
)

# CELL 5 — DATA CLEANING


initial_rows = len(df)

# Remove records with invalid timestamps
df = df.dropna(subset=["Timestamp"])

# Remove duplicate complete rows
df = df.drop_duplicates()

# Remove duplicate IDs if present
df = df.drop_duplicates(
    subset=["_id"],
    keep="first"
)

# Negative counts are invalid
df.loc[
    df["Sales Count"] < 0,
    "Sales Count"
] = np.nan

df.loc[
    df["Redemption Count"] < 0,
    "Redemption Count"
] = np.nan

# Fill missing count values with zero
df["Sales Count"] = df["Sales Count"].fillna(0)
df["Redemption Count"] = df["Redemption Count"].fillna(0)

# Make sure counts are non-negative
df["Sales Count"] = df["Sales Count"].clip(lower=0)
df["Redemption Count"] = df["Redemption Count"].clip(lower=0)

# Sort chronologically
df = (
    df.sort_values("Timestamp")
      .reset_index(drop=True)
)

print("Rows before cleaning:", initial_rows)
print("Rows after cleaning:", len(df))
print("Rows removed:", initial_rows - len(df))

# CELL 6 — 15-MINUTE INTERVAL VALIDATION


unique_timestamps = (
    df["Timestamp"]
    .drop_duplicates()
    .sort_values()
)

interval_difference = (
    unique_timestamps.diff()
    .dropna()
)

print("Most common intervals:")
st.write(
    interval_difference
    .value_counts()
    .head(10)
)

expected_interval = pd.Timedelta(minutes=15)

irregular_count = (
    interval_difference != expected_interval
).sum()

print(
    "\nNumber of irregular timestamp gaps:",
    irregular_count
)

# Create complete 15-minute timeline
complete_timeline = pd.date_range(
    start=unique_timestamps.min(),
    end=unique_timestamps.max(),
    freq="15min"
)

existing_timeline = pd.DatetimeIndex(
    unique_timestamps
)

missing_timestamps = (
    complete_timeline
    .difference(existing_timeline)
)

print(
    "Expected 15-minute timestamps:",
    len(complete_timeline)
)

print(
    "Observed timestamps:",
    len(existing_timeline)
)

print(
    "Missing timestamps:",
    len(missing_timestamps)
)

if len(missing_timestamps) > 0:
    print("\nFirst missing timestamps:")
    st.write(
        pd.DataFrame({
            "Missing_Timestamp":
            missing_timestamps[:20]
        })
    )

# CELL 7 — TEMPORAL FEATURES


df["Date"] = df["Timestamp"].dt.date
df["Year"] = df["Timestamp"].dt.year
df["Month"] = df["Timestamp"].dt.month
df["Month_Name"] = df["Timestamp"].dt.month_name()
df["Day"] = df["Timestamp"].dt.day
df["Hour"] = df["Timestamp"].dt.hour
df["Minute"] = df["Timestamp"].dt.minute

df["Day_of_Week"] = (
    df["Timestamp"].dt.day_name()
)

df["Day_of_Week_Number"] = (
    df["Timestamp"].dt.dayofweek
)

df["Is_Weekend"] = (
    df["Day_of_Week_Number"] >= 5
).astype(int)

df["Day_Type"] = np.where(
    df["Is_Weekend"] == 1,
    "Weekend",
    "Weekday"
)



# Time bands


def assign_time_band(hour):

    if 5 <= hour < 12:
        return "Morning"

    elif 12 <= hour < 17:
        return "Afternoon"

    elif 17 <= hour < 22:
        return "Evening"

    else:
        return "Night"


df["Time_Band"] = (
    df["Hour"]
    .apply(assign_time_band)
)



# Seasons


def assign_season(month):

    if month in [3, 4, 5]:
        return "Spring"

    elif month in [6, 7, 8]:
        return "Summer"

    elif month in [9, 10, 11]:
        return "Fall"

    else:
        return "Winter"


df["Season"] = (
    df["Month"]
    .apply(assign_season)
)

st.write(df.head())

# CELL 8 — CORE ANALYTICAL FEATURES


# Total Activity Load
df["Total_Activity_Load"] = (
    df["Sales Count"] +
    df["Redemption Count"]
)

# Redemption Pressure Ratio
df["Redemption_Pressure_Ratio"] = (
    df["Redemption Count"] /
    (df["Sales Count"] + 1)
)

# Zero activity
df["Zero_Activity_Flag"] = (
    df["Total_Activity_Load"] == 0
).astype(int)

st.write(
    df[
        [
            "Timestamp",
            "Sales Count",
            "Redemption Count",
            "Total_Activity_Load",
            "Redemption_Pressure_Ratio"
        ]
    ].head(15)
)

# CELL 9 — ROLLING BASELINE

# 15-minute data:
# 4 intervals = 1 hour
# 16 intervals = 4 hours
# 96 intervals = 24 hours

df["Rolling_1H_Load"] = (
    df["Total_Activity_Load"]
    .rolling(
        window=4,
        min_periods=1
    )
    .mean()
)

df["Rolling_4H_Load"] = (
    df["Total_Activity_Load"]
    .rolling(
        window=16,
        min_periods=1
    )
    .mean()
)

df["Rolling_24H_Load"] = (
    df["Total_Activity_Load"]
    .rolling(
        window=96,
        min_periods=1
    )
    .mean()
)

# Rolling standard deviation
df["Rolling_24H_Std"] = (
    df["Total_Activity_Load"]
    .rolling(
        window=96,
        min_periods=20
    )
    .std()
)

st.write(
    df[
        [
            "Timestamp",
            "Total_Activity_Load",
            "Rolling_1H_Load",
            "Rolling_4H_Load",
            "Rolling_24H_Load"
        ]
    ].head(20)
)

# CELL 10 — OPERATIONAL LOAD INDEX


# ------------------------------------------------------------
# Component 1: historical percentile rank

df["Load_Percentile"] = (
    df["Total_Activity_Load"]
    .rank(pct=True)
)


# ------------------------------------------------------------
# Component 2: deviation from 24-hour rolling baseline


df["Baseline_Deviation"] = (
    df["Total_Activity_Load"] -
    df["Rolling_24H_Load"]
)

df["Baseline_Deviation_Ratio"] = (
    df["Baseline_Deviation"] /
    (df["Rolling_24H_Load"] + 1)
)


# Convert deviation into 0–1 pressure score
deviation_score = (
    df["Baseline_Deviation_Ratio"]
    .clip(-1, 1)
    .add(1)
    .div(2)
)


# ------------------------------------------------------------
# Operational Load Index


df["OLI"] = (
    0.70 * df["Load_Percentile"] +
    0.30 * deviation_score
) * 100

df["OLI"] = (
    df["OLI"]
    .clip(0, 100)
)

st.write(
    df[
        [
            "Timestamp",
            "Total_Activity_Load",
            "Rolling_24H_Load",
            "Baseline_Deviation_Ratio",
            "OLI"
        ]
    ].head(20)
)

# CELL 11 — ADAPTIVE THRESHOLDS


# Historical percentile-based thresholds

CONGESTION_THRESHOLD = (
    df["OLI"].quantile(0.90)
)

HIGH_LOAD_THRESHOLD = (
    df["OLI"].quantile(0.75)
)

IDLE_THRESHOLD = (
    df["OLI"].quantile(0.10)
)

print(
    f"Congestion threshold: "
    f"{CONGESTION_THRESHOLD:.2f}"
)

print(
    f"High-load threshold: "
    f"{HIGH_LOAD_THRESHOLD:.2f}"
)

print(
    f"Idle threshold: "
    f"{IDLE_THRESHOLD:.2f}"
)


df["Congestion_Flag"] = (
    df["OLI"] >= CONGESTION_THRESHOLD
).astype(int)

df["High_Load_Flag"] = (
    df["OLI"] >= HIGH_LOAD_THRESHOLD
).astype(int)

df["Idle_Flag"] = (
    df["OLI"] <= IDLE_THRESHOLD
).astype(int)


df["Operational_Status"] = np.select(
    [
        df["Congestion_Flag"] == 1,
        df["High_Load_Flag"] == 1,
        df["Idle_Flag"] == 1
    ],
    [
        "Congestion",
        "High Load",
        "Idle"
    ],
    default="Normal"
)

st.write(
    df[
        [
            "Timestamp",
            "OLI",
            "Operational_Status"
        ]
    ].head(20)
)

# CELL 12 — CONGESTION EPISODES


df["Congestion_Group"] = (
    df["Congestion_Flag"]
    .ne(df["Congestion_Flag"].shift())
    .cumsum()
)

congestion_periods = (
    df[df["Congestion_Flag"] == 1]
    .groupby("Congestion_Group")
    .agg(
        Start=("Timestamp", "min"),
        End=("Timestamp", "max"),
        Intervals=("Timestamp", "count"),
        Average_OLI=("OLI", "mean"),
        Maximum_OLI=("OLI", "max"),
        Peak_Activity=("Total_Activity_Load", "max")
    )
    .reset_index(drop=True)
)

congestion_periods["Duration_Minutes"] = (
    congestion_periods["Intervals"] * 15
)

congestion_periods = (
    congestion_periods
    .sort_values(
        "Duration_Minutes",
        ascending=False
    )
    .reset_index(drop=True)
)

print("Top congestion episodes:")
st.write(
    congestion_periods.head(20)
)

# CELL 13 — SUSTAINED IDLE PERIODS


df["Idle_Group"] = (
    df["Idle_Flag"]
    .ne(df["Idle_Flag"].shift())
    .cumsum()
)

idle_periods = (
    df[df["Idle_Flag"] == 1]
    .groupby("Idle_Group")
    .agg(
        Start=("Timestamp", "min"),
        End=("Timestamp", "max"),
        Intervals=("Timestamp", "count"),
        Average_OLI=("OLI", "mean"),
        Minimum_OLI=("OLI", "min"),
        Average_Activity=("Total_Activity_Load", "mean")
    )
    .reset_index(drop=True)
)

idle_periods["Duration_Minutes"] = (
    idle_periods["Intervals"] * 15
)

# Focus on sustained periods >= 45 minutes
sustained_idle_periods = (
    idle_periods[
        idle_periods["Duration_Minutes"] >= 45
    ]
    .sort_values(
        "Duration_Minutes",
        ascending=False
    )
    .reset_index(drop=True)
)

print(
    "Sustained idle periods (>=45 minutes):"
)

st.write(
    sustained_idle_periods.head(20)
)

# CELL 14 — HOURLY AGGREGATION


hourly = (
    df.set_index("Timestamp")
    .resample("1h")
    .agg(
        Sales_Count=("Sales Count", "sum"),
        Redemption_Count=("Redemption Count", "sum"),
        Total_Activity_Load=("Total_Activity_Load", "sum"),
        Average_OLI=("OLI", "mean"),
        Maximum_OLI=("OLI", "max"),
        Congestion_Intervals=("Congestion_Flag", "sum"),
        Idle_Intervals=("Idle_Flag", "sum")
    )
    .reset_index()
)

hourly["Year"] = (
    hourly["Timestamp"].dt.year
)

hourly["Month"] = (
    hourly["Timestamp"].dt.month
)

hourly["Month_Name"] = (
    hourly["Timestamp"].dt.month_name()
)

hourly["Hour"] = (
    hourly["Timestamp"].dt.hour
)

hourly["Day_of_Week"] = (
    hourly["Timestamp"].dt.day_name()
)

hourly["Day_Type"] = np.where(
    hourly["Timestamp"].dt.dayofweek >= 5,
    "Weekend",
    "Weekday"
)

st.write(hourly.head())

# CELL 15 — DAILY AGGREGATION


daily = (
    df.set_index("Timestamp")
    .resample("1D")
    .agg(
        Sales_Count=("Sales Count", "sum"),
        Redemption_Count=("Redemption Count", "sum"),
        Total_Activity_Load=("Total_Activity_Load", "sum"),
        Average_OLI=("OLI", "mean"),
        Maximum_OLI=("OLI", "max"),
        Congestion_Intervals=("Congestion_Flag", "sum"),
        Idle_Intervals=("Idle_Flag", "sum")
    )
    .reset_index()
)

daily["Year"] = (
    daily["Timestamp"].dt.year
)

daily["Month"] = (
    daily["Timestamp"].dt.month
)

daily["Month_Name"] = (
    daily["Timestamp"].dt.month_name()
)

daily["Day_of_Week"] = (
    daily["Timestamp"].dt.day_name()
)

daily["Day_Type"] = np.where(
    daily["Timestamp"].dt.dayofweek >= 5,
    "Weekend",
    "Weekday"
)

st.write(daily.head())

# CELL 16 — CAPACITY UTILIZATION PROXY


print("""
IMPORTANT:
The dataset does not contain official vessel capacity.

Therefore this metric is an analytical proxy, not an observed
physical ferry capacity utilization percentage.
""")

# Use redemption activity as the passenger-throughput proxy.
# Normalize against the historical 99th percentile to avoid
# extreme outliers dominating the scale.

reference_load = (
    df["Redemption Count"]
    .quantile(0.99)
)

df["Capacity_Utilization_Proxy_%"] = (
    df["Redemption Count"] /
    (reference_load + 1)
) * 100

df["Capacity_Utilization_Proxy_%"] = (
    df["Capacity_Utilization_Proxy_%"]
    .clip(0, 100)
)

print(
    "Reference historical passenger load (99th percentile):",
    round(reference_load, 2)
)

st.write(
    df[
        [
            "Timestamp",
            "Redemption Count",
            "Capacity_Utilization_Proxy_%"
        ]
    ].head(15)
)

# CELL 17 — CONGESTION PRESSURE INDEX


# CPI combines:
# 1. OLI
# 2. baseline deviation
# 3. redemption pressure

redemption_pressure_normalized = (
    df["Redemption_Pressure_Ratio"]
    .rank(pct=True)
)

baseline_pressure = (
    df["Baseline_Deviation_Ratio"]
    .clip(lower=0)
    .rank(pct=True)
)

df["Congestion_Pressure_Index"] = (
    0.60 * (df["OLI"] / 100) +
    0.25 * baseline_pressure +
    0.15 * redemption_pressure_normalized
) * 100

df["Congestion_Pressure_Index"] = (
    df["Congestion_Pressure_Index"]
    .clip(0, 100)
)

st.write(
    df[
        [
            "Timestamp",
            "OLI",
            "Redemption_Pressure_Ratio",
            "Congestion_Pressure_Index"
        ]
    ].head(15)
)

# CELL 18 — PEAK STRAIN DURATION

if len(congestion_periods) > 0:

    peak_strain_duration = (
        congestion_periods[
            "Duration_Minutes"
        ].max()
    )

else:

    peak_strain_duration = 0


print(
    "Longest sustained congestion:",
    peak_strain_duration,
    "minutes"
)

# CELL 19 — OPERATIONAL VARIABILITY


# Coefficient of variation of activity
activity_mean = (
    df["Total_Activity_Load"].mean()
)

activity_std = (
    df["Total_Activity_Load"].std()
)

coefficient_of_variation = (
    activity_std /
    (activity_mean + 1e-9)
)

# Convert to a 0–100 score.
# Higher = greater variability.
operational_variability_score = min(
    coefficient_of_variation * 100,
    100
)

print(
    "Operational Variability Score:",
    round(
        operational_variability_score,
        2
    )
)

# CELL 20 — ANOMALY DETECTION


df["Activity_ZScore"] = (
    df["Total_Activity_Load"] -
    df["Rolling_24H_Load"]
) / (
    df["Rolling_24H_Std"] + 1e-6
)

df["Anomaly_Flag"] = (
    df["Activity_ZScore"].abs() >= 3
).astype(int)

print(
    "Statistical anomalies detected:",
    df["Anomaly_Flag"].sum()
)

anomalies = (
    df[df["Anomaly_Flag"] == 1]
    [
        [
            "Timestamp",
            "Total_Activity_Load",
            "Rolling_24H_Load",
            "Activity_ZScore",
            "OLI"
        ]
    ]
    .sort_values(
        "Activity_ZScore",
        ascending=False
    )
)

st.write(anomalies.head(20))

# CELL 21 — WEEKDAY VS WEEKEND


weekday_weekend = (
    df.groupby("Day_Type")
    .agg(
        Average_Activity=(
            "Total_Activity_Load",
            "mean"
        ),
        Peak_Activity=(
            "Total_Activity_Load",
            "max"
        ),
        Average_OLI=(
            "OLI",
            "mean"
        ),
        Congestion_Rate=(
            "Congestion_Flag",
            "mean"
        ),
        Idle_Rate=(
            "Idle_Flag",
            "mean"
        )
    )
    .reset_index()
)

weekday_weekend["Congestion_Rate"] *= 100
weekday_weekend["Idle_Rate"] *= 100

st.write(weekday_weekend)

# CELL 22 — SEASONAL ANALYSIS


season_analysis = (
    df.groupby("Season")
    .agg(
        Average_Activity=(
            "Total_Activity_Load",
            "mean"
        ),
        Peak_Activity=(
            "Total_Activity_Load",
            "max"
        ),
        Average_OLI=(
            "OLI",
            "mean"
        ),
        Congestion_Rate=(
            "Congestion_Flag",
            "mean"
        ),
        Idle_Rate=(
            "Idle_Flag",
            "mean"
        )
    )
    .reset_index()
)

season_analysis["Congestion_Rate"] *= 100
season_analysis["Idle_Rate"] *= 100

season_order = [
    "Spring",
    "Summer",
    "Fall",
    "Winter"
]

season_analysis["Season"] = pd.Categorical(
    season_analysis["Season"],
    categories=season_order,
    ordered=True
)

season_analysis = (
    season_analysis
    .sort_values("Season")
)

st.write(season_analysis)

# CELL 23 — TIME BAND ANALYSIS

time_band_analysis = (
    df.groupby("Time_Band")
    .agg(
        Average_Activity=(
            "Total_Activity_Load",
            "mean"
        ),
        Peak_Activity=(
            "Total_Activity_Load",
            "max"
        ),
        Average_OLI=(
            "OLI",
            "mean"
        ),
        Congestion_Rate=(
            "Congestion_Flag",
            "mean"
        ),
        Idle_Rate=(
            "Idle_Flag",
            "mean"
        )
    )
    .reset_index()
)

time_band_order = [
    "Morning",
    "Afternoon",
    "Evening",
    "Night"
]

time_band_analysis["Time_Band"] = pd.Categorical(
    time_band_analysis["Time_Band"],
    categories=time_band_order,
    ordered=True
)

time_band_analysis["Congestion_Rate"] *= 100
time_band_analysis["Idle_Rate"] *= 100

time_band_analysis = (
    time_band_analysis
    .sort_values("Time_Band")
)

st.write(time_band_analysis)

# CELL 24 — MONTHLY ANALYSIS


monthly_analysis = (
    df.groupby("Month")
    .agg(
        Average_Activity=(
            "Total_Activity_Load",
            "mean"
        ),
        Total_Activity=(
            "Total_Activity_Load",
            "sum"
        ),
        Average_OLI=(
            "OLI",
            "mean"
        ),
        Congestion_Rate=(
            "Congestion_Flag",
            "mean"
        ),
        Idle_Rate=(
            "Idle_Flag",
            "mean"
        )
    )
    .reset_index()
)

monthly_analysis["Month_Name"] = (
    pd.to_datetime(
        monthly_analysis["Month"],
        format="%m"
    ).dt.month_name()
)

monthly_analysis["Congestion_Rate"] *= 100
monthly_analysis["Idle_Rate"] *= 100

st.write(monthly_analysis)

# CELL 25 — YEARLY TREND ANALYSIS


year_analysis = (
    df.groupby("Year")
    .agg(
        Total_Activity=(
            "Total_Activity_Load",
            "sum"
        ),
        Average_Activity=(
            "Total_Activity_Load",
            "mean"
        ),
        Peak_Activity=(
            "Total_Activity_Load",
            "max"
        ),
        Average_OLI=(
            "OLI",
            "mean"
        ),
        Congestion_Rate=(
            "Congestion_Flag",
            "mean"
        ),
        Idle_Rate=(
            "Idle_Flag",
            "mean"
        ),
        Average_Capacity_Proxy=(
            "Capacity_Utilization_Proxy_%",
            "mean"
        )
    )
    .reset_index()
)

year_analysis["Congestion_Rate"] *= 100
year_analysis["Idle_Rate"] *= 100

st.write(year_analysis)

# CELL 26 — OPERATIONAL LOAD HEATMAP


heatmap_data = (
    df.groupby(
        ["Day_of_Week", "Hour"]
    )["OLI"]
    .mean()
    .reset_index()
)

day_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

heatmap = heatmap_data.pivot(
    index="Day_of_Week",
    columns="Hour",
    values="OLI"
)

heatmap = heatmap.reindex(day_order)

plt.figure(
    figsize=(18, 7)
)

sns.heatmap(
    heatmap,
    cmap="RdYlGn_r",
    center=50,
    linewidths=0.2
)

plt.title(
    "Operational Load Index Heatmap"
)

plt.xlabel("Hour of Day")
plt.ylabel("Day of Week")

plt.tight_layout()
plt.show()

# CELL 27 — CONGESTION RATE HEATMAP


congestion_heatmap = (
    df.groupby(
        ["Day_of_Week", "Hour"]
    )["Congestion_Flag"]
    .mean()
    .reset_index()
)

congestion_pivot = congestion_heatmap.pivot(
    index="Day_of_Week",
    columns="Hour",
    values="Congestion_Flag"
)

congestion_pivot = (
    congestion_pivot
    .reindex(day_order)
    * 100
)

plt.figure(
    figsize=(18, 7)
)

sns.heatmap(
    congestion_pivot,
    cmap="Reds",
    annot=False,
    linewidths=0.2
)

plt.title(
    "Congestion Rate Heatmap (%)"
)

plt.xlabel("Hour of Day")
plt.ylabel("Day of Week")

plt.tight_layout()
plt.show()

# CELL 28 — IDLE RATE HEATMAP


idle_heatmap = (
    df.groupby(
        ["Day_of_Week", "Hour"]
    )["Idle_Flag"]
    .mean()
    .reset_index()
)

idle_pivot = idle_heatmap.pivot(
    index="Day_of_Week",
    columns="Hour",
    values="Idle_Flag"
)

idle_pivot = (
    idle_pivot
    .reindex(day_order)
    * 100
)

plt.figure(
    figsize=(18, 7)
)

sns.heatmap(
    idle_pivot,
    cmap="Blues",
    annot=False,
    linewidths=0.2
)

plt.title(
    "Idle Capacity Rate Heatmap (%)"
)

plt.xlabel("Hour of Day")
plt.ylabel("Day of Week")

plt.tight_layout()
plt.show()

# CELL 29 — DAILY ACTIVITY TIMELINE

fig = px.line(
    daily,
    x="Timestamp",
    y="Total_Activity_Load",
    title="Daily Ferry Activity Load — 2015–2025",
    labels={
        "Timestamp": "Date",
        "Total_Activity_Load": "Activity Load"
    }
)

fig.update_layout(
    height=550,
    hovermode="x unified"
)

fig.show()

# CELL 30 — OLI TIMELINE

# Plot a sampled version for performance
plot_df = df.iloc[::20].copy()

fig = px.line(
    plot_df,
    x="Timestamp",
    y="OLI",
    title="Operational Load Index — 2015–2025"
)

fig.add_hline(
    y=CONGESTION_THRESHOLD,
    line_dash="dash",
    annotation_text="Congestion Threshold"
)

fig.add_hline(
    y=IDLE_THRESHOLD,
    line_dash="dash",
    annotation_text="Idle Threshold"
)

fig.update_layout(
    height=550,
    hovermode="x unified"
)

fig.show()

# CELL 31 — SEASONAL COMPARISON

fig = px.bar(
    season_analysis,
    x="Season",
    y="Average_OLI",
    text_auto=".2f",
    title="Average Operational Load by Season"
)

fig.update_layout(
    height=500
)

fig.show()

# CELL 32 — WEEKDAY VS WEEKEND

fig = px.bar(
    weekday_weekend,
    x="Day_Type",
    y="Average_Activity",
    text_auto=".2f",
    title="Average Ferry Activity: Weekday vs Weekend"
)

fig.update_layout(
    height=500
)

fig.show()

# CELL 33 — TOP CONGESTION EPISODES

top_congestion = (
    congestion_periods
    .head(20)
    .copy()
)

st.write(top_congestion)

if len(top_congestion) > 0:

    fig = px.bar(
        top_congestion,
        x="Start",
        y="Duration_Minutes",
        hover_data=[
            "End",
            "Average_OLI",
            "Maximum_OLI",
            "Peak_Activity"
        ],
        title="Top Sustained Congestion Episodes"
    )

    fig.update_layout(
        height=550
    )

    fig.show()

# CELL 34 — KPI ENGINE

total_activity = (
    df["Total_Activity_Load"].sum()
)

average_activity = (
    df["Total_Activity_Load"].mean()
)

peak_activity = (
    df["Total_Activity_Load"].max()
)

congestion_percentage = (
    df["Congestion_Flag"].mean() * 100
)

idle_percentage = (
    df["Idle_Flag"].mean() * 100
)

anomaly_percentage = (
    df["Anomaly_Flag"].mean() * 100
)

average_capacity_proxy = (
    df["Capacity_Utilization_Proxy_%"].mean()
)

peak_capacity_proxy = (
    df["Capacity_Utilization_Proxy_%"].max()
)


kpi_table = pd.DataFrame({
    "KPI": [
        "Total Activity Load",
        "Average Activity / 15-min",
        "Peak Activity / 15-min",
        "Congestion Pressure %",
        "Idle Capacity %",
        "Peak Strain Duration (min)",
        "Operational Variability Score",
        "Average Capacity Utilization Proxy %",
        "Peak Capacity Utilization Proxy %",
        "Statistical Anomaly %"
    ],

    "Value": [
        total_activity,
        average_activity,
        peak_activity,
        congestion_percentage,
        idle_percentage,
        peak_strain_duration,
        operational_variability_score,
        average_capacity_proxy,
        peak_capacity_proxy,
        anomaly_percentage
    ]
})

st.write(kpi_table)

# CELL 35 — AUTOMATIC INSIGHT ENGINE

highest_season = (
    season_analysis
    .sort_values(
        "Average_OLI",
        ascending=False
    )
    .iloc[0]
)

lowest_season = (
    season_analysis
    .sort_values(
        "Average_OLI",
        ascending=True
    )
    .iloc[0]
)

highest_time_band = (
    time_band_analysis
    .sort_values(
        "Average_OLI",
        ascending=False
    )
    .iloc[0]
)

highest_day = (
    weekday_weekend
    .sort_values(
        "Average_Activity",
        ascending=False
    )
    .iloc[0]
)

peak_year = (
    year_analysis
    .sort_values(
        "Average_OLI",
        ascending=False
    )
    .iloc[0]
)

lowest_year = (
    year_analysis
    .sort_values(
        "Average_OLI",
        ascending=True
    )
    .iloc[0]
)


print("=" * 75)
print("AUTOMATED OPERATIONAL INSIGHTS")
print("=" * 75)

print(
    f"\n1. Highest-pressure season: "
    f"{highest_season['Season']}"
)

print(
    f"   Average OLI: "
    f"{highest_season['Average_OLI']:.2f}"
)

print(
    f"\n2. Lowest-pressure season: "
    f"{lowest_season['Season']}"
)

print(
    f"   Average OLI: "
    f"{lowest_season['Average_OLI']:.2f}"
)

print(
    f"\n3. Highest-pressure time band: "
    f"{highest_time_band['Time_Band']}"
)

print(
    f"   Average OLI: "
    f"{highest_time_band['Average_OLI']:.2f}"
)

print(
    f"\n4. Higher-activity day type: "
    f"{highest_day['Day_Type']}"
)

print(
    f"   Average activity: "
    f"{highest_day['Average_Activity']:.2f}"
)

print(
    f"\n5. Highest-pressure year: "
    f"{int(peak_year['Year'])}"
)

print(
    f"   Average OLI: "
    f"{peak_year['Average_OLI']:.2f}"
)

print(
    f"\n6. Lowest-pressure year: "
    f"{int(lowest_year['Year'])}"
)

print(
    f"   Average OLI: "
    f"{lowest_year['Average_OLI']:.2f}"
)

print("=" * 75)

# CELL 36 — OPERATIONAL RECOMMENDATIONS

print("=" * 75)
print("DATA-DRIVEN OPERATIONAL RECOMMENDATIONS")
print("=" * 75)

print(f"""
1. CONGESTION MANAGEMENT
   The system identified {congestion_percentage:.2f}% of
   observed intervals as high-pressure/congestion intervals.
   Recurring periods should be evaluated for schedule and
   passenger-flow optimization.

2. IDLE CAPACITY MANAGEMENT
   Approximately {idle_percentage:.2f}% of intervals fall within
   the historical low-load range. Sustained low-load windows
   should be reviewed for possible resource optimization.

3. SEASONAL RESOURCE ALLOCATION
   {highest_season['Season']} shows the highest average
   operational pressure in the historical dataset.
   Seasonal planning should account for this pattern.

4. TEMPORAL PLANNING
   The {highest_time_band['Time_Band']} period has the highest
   average operational pressure among the defined time bands.

5. PEAK STRAIN MANAGEMENT
   The longest detected congestion episode lasted
   {peak_strain_duration:.0f} minutes.
   Long-duration recurring episodes should receive priority.

6. ANOMALY INVESTIGATION
   Statistical anomalies should be cross-checked against
   holidays, weather, events, service changes and other
   external operational factors before making decisions.

7. LONG-TERM PLANNING
   The 2015–2025 trend analysis can support seasonal planning,
   staffing decisions and operational resource allocation.
""")

print("=" * 75)

# CELL 37 — EXPORT PROCESSED DATA

df.to_csv(
    "ferry_processed_15min.csv",
    index=False
)

hourly.to_csv(
    "ferry_hourly_analysis.csv",
    index=False
)

daily.to_csv(
    "ferry_daily_analysis.csv",
    index=False
)

year_analysis.to_csv(
    "ferry_yearly_analysis.csv",
    index=False
)

season_analysis.to_csv(
    "ferry_seasonal_analysis.csv",
    index=False
)

time_band_analysis.to_csv(
    "ferry_timeband_analysis.csv",
    index=False
)

weekday_weekend.to_csv(
    "ferry_weekday_weekend_analysis.csv",
    index=False
)

congestion_periods.to_csv(
    "ferry_congestion_periods.csv",
    index=False
)

sustained_idle_periods.to_csv(
    "ferry_idle_periods.csv",
    index=False
)

anomalies.to_csv(
    "ferry_anomalies.csv",
    index=False
)

kpi_table.to_csv(
    "ferry_kpi_report.csv",
    index=False
)

print("All analytical CSV files created successfully.")

# CELL 38 — EXCEL REPORT

excel_file = (
    "Ferry_Operational_Efficiency_Report.xlsx"
)

with pd.ExcelWriter(
    excel_file,
    engine="openpyxl"
) as writer:

    kpi_table.to_excel(
        writer,
        sheet_name="KPI_Report",
        index=False
    )

    df.to_excel(
        writer,
        sheet_name="Processed_15Min",
        index=False
    )

    hourly.to_excel(
        writer,
        sheet_name="Hourly",
        index=False
    )

    daily.to_excel(
        writer,
        sheet_name="Daily",
        index=False
    )

    weekday_weekend.to_excel(
        writer,
        sheet_name="Weekday_Weekend",
        index=False
    )

    season_analysis.to_excel(
        writer,
        sheet_name="Seasonal",
        index=False
    )

    time_band_analysis.to_excel(
        writer,
        sheet_name="Time_Bands",
        index=False
    )

    monthly_analysis.to_excel(
        writer,
        sheet_name="Monthly",
        index=False
    )

    year_analysis.to_excel(
        writer,
        sheet_name="Yearly",
        index=False
    )

    congestion_periods.to_excel(
        writer,
        sheet_name="Congestion",
        index=False
    )

    sustained_idle_periods.to_excel(
        writer,
        sheet_name="Idle_Periods",
        index=False
    )

    anomalies.to_excel(
        writer,
        sheet_name="Anomalies",
        index=False
    )

print(
    "Excel report created:",
    excel_file
)

# CELL 39 — DOWNLOAD EXCEL REPORT

files.download(
    "Ferry_Operational_Efficiency_Report.xlsx"
)

"""For streamlit dashboard:"""

import os

print(os.listdir("/content"))

from google.colab import files

uploaded = files.upload()

import os

print("Files currently in /content:")
for f in os.listdir("/content"):
    print(repr(f))

import os

py_files = [
    f for f in os.listdir("/content")
    if f.lower().endswith(".py")
]

print("Python files found:", py_files)

import os
import shutil

py_files = [
    f for f in os.listdir("/content")
    if f.lower().endswith(".py")
]

if not py_files:
    print("❌ No Python file was uploaded.")
    print("Please upload app.py first.")
else:
    source = "/content/" + py_files[0]
    destination = "/content/app.py"

    if source != destination:
        shutil.copy(source, destination)

    print("✅ Dashboard file is ready!")
    print("Location:", destination)
    print("Exists:", os.path.exists(destination))

# CREATE THE STREAMLIT APP FILE
# This cell will create /content/app.py

app_code = r'''
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

st.set_page_config(
    page_title="Ferry Capacity & Operational Efficiency Analytics",
    page_icon="⛴️",
    layout="wide"
)

st.title("⛴️ Ferry Capacity Utilization & Operational Efficiency Analytics")
st.caption(
    "Jack Layton Ferry Terminal | Toronto Ferry Operations | 2015–2025"
)

uploaded_file = st.file_uploader(
    "Upload Toronto Island Ferry Tickets CSV",
    type=["csv"]
)

if uploaded_file is None:
    st.info("Please upload the Toronto Island Ferry Tickets CSV file.")
    st.stop()

df = pd.read_csv(uploaded_file)

# -----------------------------
# DATA CLEANING
# -----------------------------

df.columns = df.columns.str.strip()

df["Timestamp"] = pd.to_datetime(
    df["Timestamp"],
    errors="coerce"
)

df["Sales Count"] = pd.to_numeric(
    df["Sales Count"],
    errors="coerce"
).fillna(0)

df["Redemption Count"] = pd.to_numeric(
    df["Redemption Count"],
    errors="coerce"
).fillna(0)

df = df.dropna(subset=["Timestamp"])
df = df.drop_duplicates()

df["Sales Count"] = df["Sales Count"].clip(lower=0)
df["Redemption Count"] = df["Redemption Count"].clip(lower=0)

df = df.sort_values("Timestamp")

# -----------------------------
# FEATURES
# -----------------------------

df["Total Activity Load"] = (
    df["Sales Count"] +
    df["Redemption Count"]
)

df["Redemption Pressure Ratio"] = (
    df["Redemption Count"] /
    (df["Sales Count"] + 1)
)

df["Year"] = df["Timestamp"].dt.year
df["Month"] = df["Timestamp"].dt.month
df["Hour"] = df["Timestamp"].dt.hour

df["Day Type"] = np.where(
    df["Timestamp"].dt.dayofweek >= 5,
    "Weekend",
    "Weekday"
)

def season(month):
    if month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    elif month in [9, 10, 11]:
        return "Fall"
    else:
        return "Winter"

df["Season"] = df["Month"].apply(season)

def time_band(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 22:
        return "Evening"
    return "Night"

df["Time Band"] = df["Hour"].apply(time_band)

# -----------------------------
# OPERATIONAL LOAD INDEX
# -----------------------------

df["Rolling Load"] = (
    df["Total Activity Load"]
    .rolling(96, min_periods=1)
    .mean()
)

df["Load Percentile"] = (
    df["Total Activity Load"]
    .rank(pct=True)
)

deviation = (
    df["Total Activity Load"] -
    df["Rolling Load"]
) / (df["Rolling Load"] + 1)

deviation_score = (
    deviation.clip(-1, 1) + 1
) / 2

df["OLI"] = (
    0.70 * df["Load Percentile"] +
    0.30 * deviation_score
) * 100

df["OLI"] = df["OLI"].clip(0, 100)

congestion_threshold = df["OLI"].quantile(0.90)
idle_threshold = df["OLI"].quantile(0.10)

df["Congestion"] = (
    df["OLI"] >= congestion_threshold
)

df["Idle"] = (
    df["OLI"] <= idle_threshold
)

# Capacity proxy
reference_load = df["Redemption Count"].quantile(0.99)

df["Capacity Utilization Proxy"] = (
    df["Redemption Count"] /
    (reference_load + 1)
) * 100

df["Capacity Utilization Proxy"] = (
    df["Capacity Utilization Proxy"].clip(0, 100)
)

# -----------------------------
# SIDEBAR
# -----------------------------

st.sidebar.header("Dashboard Filters")

min_date = df["Timestamp"].min().date()
max_date = df["Timestamp"].max().date()

date_range = st.sidebar.date_input(
    "Date Range",
    value=(min_date, max_date),
    min_value=min_date,
    max_value=max_date
)

season_options = [
    "All",
    "Spring",
    "Summer",
    "Fall",
    "Winter"
]

selected_season = st.sidebar.selectbox(
    "Season",
    season_options
)

granularity = st.sidebar.radio(
    "Granularity",
    ["15-Minute", "Hourly", "Daily"]
)

filtered = df.copy()

if isinstance(date_range, tuple) and len(date_range) == 2:
    start_date, end_date = date_range

    filtered = filtered[
        (filtered["Timestamp"].dt.date >= start_date) &
        (filtered["Timestamp"].dt.date <= end_date)
    ]

if selected_season != "All":
    filtered = filtered[
        filtered["Season"] == selected_season
    ]

# -----------------------------
# KPI CARDS
# -----------------------------

st.subheader("Key Performance Indicators")

col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    st.metric(
        "Total Activity",
        f"{filtered['Total Activity Load'].sum():,.0f}"
    )

with col2:
    st.metric(
        "Average OLI",
        f"{filtered['OLI'].mean():.1f}"
    )

with col3:
    congestion_rate = filtered["Congestion"].mean() * 100

    st.metric(
        "Congestion Rate",
        f"{congestion_rate:.2f}%"
    )

with col4:
    idle_rate = filtered["Idle"].mean() * 100

    st.metric(
        "Idle Capacity %",
        f"{idle_rate:.2f}%"
    )

with col5:
    st.metric(
        "Capacity Proxy",
        f"{filtered['Capacity Utilization Proxy'].mean():.1f}%"
    )

# -----------------------------
# ALERTS
# -----------------------------

st.subheader("Operational Alerts")

if congestion_rate >= 10:
    st.error(
        f"🚨 High congestion pressure detected: "
        f"{congestion_rate:.2f}% of observed intervals."
    )
else:
    st.success(
        f"✅ Congestion pressure is currently "
        f"{congestion_rate:.2f}%."
    )

if idle_rate >= 10:
    st.warning(
        f"⚠️ Significant idle-capacity periods detected: "
        f"{idle_rate:.2f}%."
    )

# -----------------------------
# AGGREGATION
# -----------------------------

if granularity == "15-Minute":

    plot_df = filtered.copy()

    plot_df["Period"] = (
        plot_df["Timestamp"]
        .dt.floor("15min")
    )

    plot_df = (
        plot_df.groupby("Period")
        .agg(
            Activity=("Total Activity Load", "sum"),
            OLI=("OLI", "mean")
        )
        .reset_index()
    )

elif granularity == "Hourly":

    plot_df = (
        filtered.set_index("Timestamp")
        .resample("1h")
        .agg(
            Activity=("Total Activity Load", "sum"),
            OLI=("OLI", "mean")
        )
        .reset_index()
    )

else:

    plot_df = (
        filtered.set_index("Timestamp")
        .resample("1D")
        .agg(
            Activity=("Total Activity Load", "sum"),
            OLI=("OLI", "mean")
        )
        .reset_index()
    )

# -----------------------------
# TIMELINE
# -----------------------------

st.subheader("Capacity Utilization / Activity Timeline")

fig = px.line(
    plot_df,
    x="Timestamp" if "Timestamp" in plot_df.columns else "Period",
    y="Activity",
    title=f"Ferry Activity — {granularity}"
)

st.plotly_chart(
    fig,
    use_container_width=True
)

# -----------------------------
# OLI
# -----------------------------

st.subheader("Operational Load Index")

x_col = (
    "Timestamp"
    if "Timestamp" in plot_df.columns
    else "Period"
)

fig2 = px.line(
    plot_df,
    x=x_col,
    y="OLI",
    title="Operational Load Index"
)

fig2.add_hline(
    y=congestion_threshold,
    line_dash="dash",
    annotation_text="Congestion Threshold"
)

fig2.add_hline(
    y=idle_threshold,
    line_dash="dash",
    annotation_text="Idle Threshold"
)

st.plotly_chart(
    fig2,
    use_container_width=True
)

# -----------------------------
# SEASONAL ANALYSIS
# -----------------------------

st.subheader("Seasonal Efficiency Comparison")

seasonal = (
    filtered.groupby("Season")
    .agg(
        Average_Activity=(
            "Total Activity Load",
            "mean"
        ),
        Average_OLI=("OLI", "mean"),
        Congestion_Rate=(
            "Congestion",
            "mean"
        ),
        Idle_Rate=("Idle", "mean")
    )
    .reset_index()
)

seasonal["Congestion_Rate"] *= 100
seasonal["Idle_Rate"] *= 100

fig3 = px.bar(
    seasonal,
    x="Season",
    y="Average_OLI",
    text_auto=".1f",
    title="Average Operational Load by Season"
)

st.plotly_chart(
    fig3,
    use_container_width=True
)

# -----------------------------
# WEEKDAY/WEEKEND
# -----------------------------

st.subheader("Weekday vs Weekend")

day_analysis = (
    filtered.groupby("Day Type")
    .agg(
        Average_Activity=(
            "Total Activity Load",
            "mean"
        ),
        Average_OLI=("OLI", "mean")
    )
    .reset_index()
)

fig4 = px.bar(
    day_analysis,
    x="Day Type",
    y="Average_Activity",
    text_auto=".1f",
    title="Average Activity: Weekday vs Weekend"
)

st.plotly_chart(
    fig4,
    use_container_width=True
)

# -----------------------------
# TIME BAND
# -----------------------------

st.subheader("Operational Efficiency by Time Band")

time_analysis = (
    filtered.groupby("Time Band")
    .agg(
        Average_Activity=(
            "Total Activity Load",
            "mean"
        ),
        Average_OLI=("OLI", "mean")
    )
    .reset_index()
)

fig5 = px.bar(
    time_analysis,
    x="Time Band",
    y="Average_OLI",
    text_auto=".1f",
    title="Operational Load by Time Band"
)

st.plotly_chart(
    fig5,
    use_container_width=True
)

# -----------------------------
# YEARLY TREND
# -----------------------------

st.subheader("2015–2025 Operational Trend")

yearly = (
    filtered.groupby("Year")
    .agg(
        Average_Activity=(
            "Total Activity Load",
            "mean"
        ),
        Average_OLI=("OLI", "mean")
    )
    .reset_index()
)

fig6 = px.line(
    yearly,
    x="Year",
    y="Average_OLI",
    markers=True,
    title="Year-over-Year Operational Load"
)

st.plotly_chart(
    fig6,
    use_container_width=True
)

# -----------------------------
# DATA TABLE
# -----------------------------

with st.expander("View Analytical Data"):

    st.dataframe(
        filtered.head(1000),
        use_container_width=True
    )

# -----------------------------
# DOWNLOAD
# -----------------------------

csv_data = filtered.to_csv(
    index=False
).encode("utf-8")

st.download_button(
    "⬇️ Download Filtered Data",
    data=csv_data,
    file_name="ferry_filtered_analysis.csv",
    mime="text/csv"
)

st.caption(
    "Capacity utilization is presented as a proxy because "
    "the supplied dataset does not contain official vessel capacity."
)
'''

with open("/content/app.py", "w", encoding="utf-8") as f:
    f.write(app_code)

print("✅ app.py created successfully!")
print("Location: /content/app.py")

import os
print(os.path.exists("/content/app.py"))
print(os.path.getsize("/content/app.py"), "bytes")

import os
import streamlit

print("✅ Streamlit version:", streamlit.__version__)
print("✅ app.py exists:", os.path.exists("/content/app.py"))

import subprocess
import time

# Stop any old Streamlit process
subprocess.run(["pkill", "-f", "streamlit"],
               capture_output=True)

# Start Streamlit
process = subprocess.Popen(
    [
        "streamlit",
        "run",
        "/content/app.py",
        "--server.port=8501",
        "--server.address=0.0.0.0",
        "--server.headless=true"
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

time.sleep(8)

print("🚀 Streamlit dashboard started!")
print("Port: 8501")

import subprocess
import time

# Stop old Streamlit processes
subprocess.run(
    ["pkill", "-f", "streamlit"],
    capture_output=True
)

# Start Streamlit
process = subprocess.Popen(
    [
        "streamlit",
        "run",
        "/content/app.py",
        "--server.port=8501",
        "--server.address=0.0.0.0",
        "--server.headless=true"
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

time.sleep(8)

print("✅ Streamlit is running on port 8501")


import subprocess
import re
import time

cloudflare_process = subprocess.Popen(
    [
        "/content/cloudflared",
        "tunnel",
        "--url",
        "http://127.0.0.1:8501"
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

time.sleep(8)

print("=" * 70)
print("🚢 FERRY OPERATIONAL EFFICIENCY DASHBOARD")
print("=" * 70)

# Read available output
for _ in range(30):
    line = cloudflare_process.stdout.readline()

    if not line:
        break

    print(line.strip())

    if "trycloudflare.com" in line:
        break



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.set_page_config(page_title="Ferry Analytics")
# 
# st.title("🚢 Toronto Island Ferry Analytics")
# st.success("Cloudflare Tunnel is connected successfully!")





print(df.columns.tolist())

import pandas as pd
import numpy as np

# Make sure numeric columns are numeric
numeric_kpi_cols = [
    'Redemption Count',
    'Sales Count',
    'Total_Activity_Load',
    'Rolling_1H_Load',
    'Rolling_4H_Load',
    'Rolling_24H_Load',
    'OLI',
    'Capacity_Utilization_Proxy_%',
    'Congestion_Pressure_Index',
    'Activity_ZScore'
]

for col in numeric_kpi_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# ============================================
# FERRY OPERATIONS - KEY PERFORMANCE INDICATORS
# ============================================

total_sales = df['Sales Count'].sum()
total_redemptions = df['Redemption Count'].sum()
total_activity = df['Total_Activity_Load'].sum()

avg_hourly_activity = df['Total_Activity_Load'].mean()

avg_capacity_proxy = df['Capacity_Utilization_Proxy_%'].mean()
peak_capacity_proxy = df['Capacity_Utilization_Proxy_%'].max()

avg_congestion_pressure = df['Congestion_Pressure_Index'].mean()
peak_congestion_pressure = df['Congestion_Pressure_Index'].max()

congestion_rate = df['Congestion_Flag'].mean() * 100
high_load_rate = df['High_Load_Flag'].mean() * 100
idle_rate = df['Idle_Flag'].mean() * 100
anomaly_rate = df['Anomaly_Flag'].mean() * 100

avg_oli = df['OLI'].mean()
max_oli = df['OLI'].max()

kpis = pd.DataFrame({
    'KPI': [
        'Total Sales',
        'Total Redemptions',
        'Total Activity Load',
        'Average Activity Load',
        'Average Capacity Utilization Proxy (%)',
        'Peak Capacity Utilization Proxy (%)',
        'Average Congestion Pressure',
        'Peak Congestion Pressure',
        'Congestion Rate (%)',
        'High Load Rate (%)',
        'Idle Rate (%)',
        'Anomaly Rate (%)',
        'Average OLI',
        'Maximum OLI'
    ],

    'Value': [
        total_sales,
        total_redemptions,
        total_activity,
        avg_hourly_activity,
        avg_capacity_proxy,
        peak_capacity_proxy,
        avg_congestion_pressure,
        peak_congestion_pressure,
        congestion_rate,
        high_load_rate,
        idle_rate,
        anomaly_rate,
        avg_oli,
        max_oli
    ]
})

kpis['Value'] = kpis['Value'].round(2)

st.write(kpis)


st.write(HTML(f"""
<div style="
st.write:grid;
grid-template-columns:repeat(4,1fr);
gap:15px;
margin:20px 0;
">

<div style="padding:20px;border-radius:12px;background:#f5f5f5;">
<h4>Total Sales</h4>
<h2>{total_sales:,.0f}</h2>
</div>

<div style="padding:20px;border-radius:12px;background:#f5f5f5;">
<h4>Total Redemptions</h4>
<h2>{total_redemptions:,.0f}</h2>
</div>

<div style="padding:20px;border-radius:12px;background:#f5f5f5;">
<h4>Total Activity Load</h4>
<h2>{total_activity:,.0f}</h2>
</div>

<div style="padding:20px;border-radius:12px;background:#f5f5f5;">
<h4>Avg Utilization Proxy</h4>
<h2>{avg_capacity_proxy:.2f}%</h2>
</div>

</div>
"""))

# ============================================
# PEAK OPERATIONAL PERIOD
# ============================================

hourly_analysis = (
    df.groupby('Hour')
      .agg(
          Activity_Load=('Total_Activity_Load', 'mean'),
          Utilization=('Capacity_Utilization_Proxy_%', 'mean'),
          Congestion=('Congestion_Pressure_Index', 'mean')
      )
      .reset_index()
)

peak_hour = hourly_analysis.loc[
    hourly_analysis['Activity_Load'].idxmax()
]

lowest_hour = hourly_analysis.loc[
    hourly_analysis['Activity_Load'].idxmin()
]

print("PEAK OPERATIONAL PERIOD")
print("=" * 50)

print(
    f"Peak hour: {int(peak_hour['Hour']):02d}:00"
)

print(
    f"Average activity load: "
    f"{peak_hour['Activity_Load']:.2f}"
)

print(
    f"Average utilization proxy: "
    f"{peak_hour['Utilization']:.2f}%"
)

print("\nLOWEST ACTIVITY PERIOD")
print("=" * 50)

print(
    f"Lowest hour: {int(lowest_hour['Hour']):02d}:00"
)

print(
    f"Average activity load: "
    f"{lowest_hour['Activity_Load']:.2f}"
)

day_analysis = (
    df.groupby('Day_of_Week')
      .agg(
          Activity_Load=('Total_Activity_Load', 'mean'),
          Sales=('Sales Count', 'sum'),
          Redemptions=('Redemption Count', 'sum'),
          Utilization=('Capacity_Utilization_Proxy_%', 'mean'),
          Congestion=('Congestion_Pressure_Index', 'mean')
      )
      .reset_index()
)

day_analysis = day_analysis.sort_values(
    'Activity_Load',
    ascending=False
)

st.write(day_analysis)

status_analysis = (
    df['Operational_Status']
      .value_counts()
      .reset_index()
)

status_analysis.columns = [
    'Operational Status',
    'Observations'
]

status_analysis['Percentage'] = (
    status_analysis['Observations']
    / status_analysis['Observations'].sum()
    * 100
)

status_analysis['Percentage'] = (
    status_analysis['Percentage'].round(2)
)

st.write(status_analysis)

congestion_analysis = (
    df.groupby('Congestion_Group')
      .agg(
          Observations=('Congestion_Group', 'size'),
          Avg_Load=('Total_Activity_Load', 'mean'),
          Avg_Pressure=('Congestion_Pressure_Index', 'mean')
      )
      .reset_index()
)

congestion_analysis['Percentage'] = (
    congestion_analysis['Observations']
    / len(df)
    * 100
).round(2)

st.write(congestion_analysis)

anomaly_summary = pd.DataFrame({
    'Metric': [
        'Total Observations',
        'Anomalous Observations',
        'Normal Observations',
        'Anomaly Rate (%)'
    ],

    'Value': [
        len(df),
        df['Anomaly_Flag'].sum(),
        (df['Anomaly_Flag'] == 0).sum(),
        df['Anomaly_Flag'].mean() * 100
    ]
})

anomaly_summary['Value'] = anomaly_summary['Value'].round(2)

st.write(anomaly_summary)

# ============================================
# BUSINESS INSIGHTS
# ============================================

print("\n" + "="*70)
print("FERRY OPERATIONAL BUSINESS INSIGHTS")
print("="*70)

print(
    f"\n1. DEMAND:"
    f"\n   Total activity load recorded: {total_activity:,.0f}"
)

print(
    f"\n2. UTILIZATION:"
    f"\n   Average utilization proxy: {avg_capacity_proxy:.2f}%"
    f"\n   Peak utilization proxy: {peak_capacity_proxy:.2f}%"
)

print(
    f"\n3. CONGESTION:"
    f"\n   {congestion_rate:.2f}% of observations were flagged for congestion."
)

print(
    f"\n4. HIGH LOAD:"
    f"\n   {high_load_rate:.2f}% of observations experienced high load."
)

print(
    f"\n5. IDLE PERIODS:"
    f"\n   {idle_rate:.2f}% of observations were classified as idle."
)

print(
    f"\n6. ANOMALIES:"
    f"\n   {anomaly_rate:.2f}% of observations were identified as anomalies."
)

print(
    f"\n7. PEAK PERIOD:"
    f"\n   Highest activity occurred around "
    f"{int(peak_hour['Hour']):02d}:00."
)

print("\n" + "="*70)

kpis.to_csv(
    "ferry_operational_kpis.csv",
    index=False
)

print("KPI file created successfully.")

import os

print("Dashboard file exists:", os.path.exists("app.py"))

if os.path.exists("app.py"):
    print("✅ app.py found")
else:
    print("❌ app.py not found")

import pandas as pd
import numpy as np

df_check = pd.read_csv("/content/Toronto Island Ferry Tickets.csv")

required_columns = [
    "Sales Count",
    "Redemption Count",
    "Total_Activity_Load",
    "Capacity_Utilization_Proxy_%",
    "Congestion_Pressure_Index",
    "Congestion_Flag",
    "High_Load_Flag",
    "Idle_Flag",
    "Operational_Status",
    "Anomaly_Flag"
]

missing_columns = [
    col for col in required_columns
    if col not in df_check.columns
]

print("=" * 60)
print("DASHBOARD DATA HEALTH CHECK")
print("=" * 60)

if not missing_columns:
    print("✅ All required dashboard columns are present.")
else:
    print("❌ Missing columns:")
    for col in missing_columns:
        print("   -", col)

print("\nDataset shape:", df_check.shape)
print("Missing values:", df_check.isnull().sum().sum())
print("Duplicate rows:", df_check.duplicated().sum())

print(df_check.dtypes)

print("Columns in df_check:")
print(df_check.columns.tolist())

print("\nColumns in df:")
print(df.columns.tolist())

df_check = df.copy()

# ============================================
# FINAL KPI CHECK
# ============================================

import pandas as pd
import numpy as np

kpi_columns = [
    "Sales Count",
    "Redemption Count",
    "Total_Activity_Load",
    "Capacity_Utilization_Proxy_%",
    "Congestion_Pressure_Index",
    "Congestion_Flag",
    "High_Load_Flag",
    "Idle_Flag",
    "Anomaly_Flag"
]

# Convert required columns to numeric
for col in kpi_columns:
    if col in df_check.columns:
        df_check[col] = pd.to_numeric(
            df_check[col],
            errors="coerce"
        )

# Calculate KPIs
kpis_final = {
    "Total Sales": df_check["Sales Count"].sum(),
    "Total Redemptions": df_check["Redemption Count"].sum(),
    "Total Activity Load": df_check["Total_Activity_Load"].sum(),
    "Average Utilization Proxy (%)":
        df_check["Capacity_Utilization_Proxy_%"].mean(),
    "Peak Utilization Proxy (%)":
        df_check["Capacity_Utilization_Proxy_%"].max(),
    "Average Congestion Pressure":
        df_check["Congestion_Pressure_Index"].mean(),
    "Congestion Rate (%)":
        df_check["Congestion_Flag"].mean() * 100,
    "High Load Rate (%)":
        df_check["High_Load_Flag"].mean() * 100,
    "Idle Rate (%)":
        df_check["Idle_Flag"].mean() * 100,
    "Anomaly Rate (%)":
        df_check["Anomaly_Flag"].mean() * 100
}

print("=" * 65)
print("FINAL KPI VALUES")
print("=" * 65)

for name, value in kpis_final.items():
    print(f"{name:<40}: {value:,.2f}")

print("=" * 65)

# ================================================================
# 🚢 FINAL OPERATIONAL ANALYTICS - REMAINING PROJECT REQUIREMENTS
# ================================================================

import pandas as pd
import numpy as np

print("=" * 75)
print("FERRY CAPACITY & OPERATIONAL EFFICIENCY - FINAL ANALYSIS")
print("=" * 75)


# ================================================================
# 1. FINAL REQUIRED KPIs
# ================================================================

required_numeric = [
    "Total_Activity_Load",
    "Capacity_Utilization_Proxy_%",
    "Congestion_Pressure_Index",
    "Idle_Flag",
    "High_Load_Flag",
    "Congestion_Flag",
    "Anomaly_Flag"
]

for col in required_numeric:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")


# Capacity Utilization Proxy
capacity_utilization = df[
    "Capacity_Utilization_Proxy_%"
].mean()


# Congestion Pressure Index
congestion_pressure = df[
    "Congestion_Pressure_Index"
].mean()


# Idle Capacity Percentage
idle_capacity = df[
    "Idle_Flag"
].mean() * 100


# Peak Strain Duration
high_load = df["High_Load_Flag"].fillna(0)

groups = high_load.ne(
    high_load.shift()
).cumsum()

strain = (
    df[high_load == 1]
    .groupby(groups[high_load == 1])
    .size()
)

peak_strain_intervals = (
    strain.max()
    if len(strain) > 0
    else 0
)

# Dataset is based on 15-minute intervals
peak_strain_minutes = peak_strain_intervals * 15


# Operational Variability Score
mean_load = df[
    "Total_Activity_Load"
].mean()

std_load = df[
    "Total_Activity_Load"
].std()

operational_variability = (
    (std_load / mean_load) * 100
    if mean_load != 0
    else 0
)


# Final KPI table
final_kpis = pd.DataFrame({
    "KPI": [
        "Capacity Utilization Proxy (%)",
        "Congestion Pressure Index",
        "Idle Capacity Percentage (%)",
        "Peak Strain Duration (minutes)",
        "Operational Variability Score (%)"
    ],
    "Value": [
        capacity_utilization,
        congestion_pressure,
        idle_capacity,
        peak_strain_minutes,
        operational_variability
    ]
})

final_kpis["Value"] = final_kpis["Value"].round(2)


print("\n1️⃣ FINAL REQUIRED KPIs")
print("-" * 75)

st.write(final_kpis)


# ================================================================
# 2. PEAK VS IDLE OPERATIONAL COMPARISON
# ================================================================

peak_idle = (
    df.groupby("Operational_Status")
    .agg(
        Average_Load=(
            "Total_Activity_Load",
            "mean"
        ),
        Average_Utilization=(
            "Capacity_Utilization_Proxy_%",
            "mean"
        ),
        Average_Congestion=(
            "Congestion_Pressure_Index",
            "mean"
        )
    )
    .round(2)
)

print("\n2️⃣ PEAK VS IDLE OPERATIONAL COMPARISON")
print("-" * 75)

st.write(peak_idle)


# ================================================================
# 3. CONGESTION & IDLE SUMMARY
# ================================================================

congestion_rate = (
    df["Congestion_Flag"].mean() * 100
)

high_load_rate = (
    df["High_Load_Flag"].mean() * 100
)

anomaly_rate = (
    df["Anomaly_Flag"].mean() * 100
)

congestion_idle = pd.DataFrame({
    "Metric": [
        "Congestion Rate (%)",
        "High Load Rate (%)",
        "Idle Capacity (%)",
        "Anomaly Rate (%)"
    ],
    "Value": [
        congestion_rate,
        high_load_rate,
        idle_capacity,
        anomaly_rate
    ]
})

congestion_idle["Value"] = (
    congestion_idle["Value"].round(2)
)

print("\n3️⃣ CONGESTION & IDLE SUMMARY")
print("-" * 75)

st.write(congestion_idle)


# ================================================================
# 4. PEAK AND LOW-ACTIVITY HOURS
# ================================================================

hourly_efficiency = (
    df.groupby("Hour")
    .agg(
        Activity=(
            "Total_Activity_Load",
            "mean"
        ),
        Utilization=(
            "Capacity_Utilization_Proxy_%",
            "mean"
        ),
        Congestion=(
            "Congestion_Pressure_Index",
            "mean"
        ),
        Idle=(
            "Idle_Flag",
            "mean"
        )
    )
    .round(2)
)

peak_hour = (
    hourly_efficiency["Activity"]
    .idxmax()
)

lowest_hour = (
    hourly_efficiency["Activity"]
    .idxmin()
)

print("\n4️⃣ PEAK & LOW-ACTIVITY HOURS")
print("-" * 75)

print(
    f"Peak operating hour   : {int(peak_hour):02d}:00"
)

print(
    f"Lowest activity hour  : {int(lowest_hour):02d}:00"
)

print("\nTop 10 highest-activity hours:")

st.write(
    hourly_efficiency
    .sort_values(
        "Activity",
        ascending=False
    )
    .head(10)
)


# ================================================================
# 5. FINAL BUSINESS INSIGHTS
# ================================================================

print("\n5️⃣ FINAL BUSINESS INSIGHTS")
print("-" * 75)

print(
    f"""
• Average capacity utilization proxy:
  {capacity_utilization:.2f}%

• Average congestion pressure:
  {congestion_pressure:.2f}

• Congestion rate:
  {congestion_rate:.2f}%

• Idle capacity percentage:
  {idle_capacity:.2f}%

• Longest sustained high-load period:
  {peak_strain_minutes:.0f} minutes

• Operational variability score:
  {operational_variability:.2f}%

• Peak operating hour:
  {int(peak_hour):02d}:00

• Lowest activity hour:
  {int(lowest_hour):02d}:00

• Anomaly rate:
  {anomaly_rate:.2f}%
"""
)


# ================================================================
# 6. OPERATIONAL RECOMMENDATIONS
# ================================================================

recommendations = [
    "Prioritize operational monitoring during high-load and congestion-prone periods.",

    "Use historical activity patterns to support time-based resource allocation.",

    "Review consistently idle periods for opportunities to optimize ferry deployment and staffing.",

    "Use seasonal utilization patterns when planning operational schedules.",

    "Monitor anomalous activity intervals separately from normal operational demand.",

    "Use the Capacity Utilization Proxy as an operational planning indicator rather than a direct measure of physical vessel occupancy."
]

print("\n6️⃣ OPERATIONAL RECOMMENDATIONS")
print("-" * 75)

for i, recommendation in enumerate(
    recommendations,
    start=1
):
    print(f"{i}. {recommendation}")


# ================================================================
# 7. SAVE FINAL OUTPUTS
# ================================================================

final_kpis.to_csv(
    "final_kpis.csv",
    index=False
)

peak_idle.to_csv(
    "peak_vs_idle.csv"
)

congestion_idle.to_csv(
    "congestion_idle_summary.csv",
    index=False
)

hourly_efficiency.to_csv(
    "hourly_efficiency.csv"
)

print("\n7️⃣ OUTPUT FILES")
print("-" * 75)

print("✅ final_kpis.csv")
print("✅ peak_vs_idle.csv")
print("✅ congestion_idle_summary.csv")
print("✅ hourly_efficiency.csv")


# ================================================================
# FINAL LIMITATION STATEMENT
# ================================================================

print("\n" + "=" * 75)
print("ANALYTICAL LIMITATION")
print("=" * 75)

print("""
The available ticket activity dataset does not contain vessel-level
physical capacity, vessel assignment, staffing cost, fuel cost, or
trip-level operating cost information.

Therefore, capacity utilization is represented using an activity-based
Capacity Utilization Proxy (%) rather than actual physical vessel
occupancy.

Low-utilization periods are therefore treated as an operational
efficiency indicator rather than a direct measurement of monetary
operating cost.
""")

print("=" * 75)
print("✅ FINAL ANALYTICAL SECTION COMPLETED")
print("=" * 75)

"""# 🚢 Ferry Capacity Utilization & Operational Efficiency Analytics System

## Executive Summary

### 1. Project Overview

The **Ferry Capacity Utilization & Operational Efficiency Analytics System** is a data-driven operational analytics project developed to evaluate ferry activity at the **Jack Layton Ferry Terminal**, serving Toronto Island destinations including Centre Island, Hanlan's Point, and Ward's Island.

The project transforms historical ticket sales and redemption activity into meaningful operational indicators to identify capacity pressure, congestion-prone periods, idle-capacity windows, operational variability, anomalies, and temporal efficiency patterns.

Unlike a conventional ticket-sales analysis, this project focuses on **operational efficiency and decision support**, providing analytical indicators that can support scheduling, resource allocation, capacity planning, and seasonal operational decisions.


### 2. Problem Statement

Ferry operations are affected by fixed vessel capacity, staffing constraints, seasonal fluctuations, and variations in passenger activity throughout the day.

Although historical ticket sales and redemption data are available, raw ticket counts alone do not provide sufficient insight into:

- Periods of high operational pressure
- Potential capacity under-utilization
- Congestion-prone intervals
- Idle-capacity periods
- Seasonal operational differences
- Weekday and weekend efficiency
- Operational variability
- Unusual or anomalous activity

Therefore, this project develops a structured analytical framework that converts historical ticket activity into operational efficiency indicators and decision-support metrics.


### 3. Project Objectives

#### Primary Objectives

1. Quantify ferry operational load using ticket activity data.
2. Develop an activity-based capacity utilization indicator.
3. Identify congestion-prone and high-load periods.
4. Detect sustained idle and low-activity periods.
5. Measure operational variability and stability.
6. Compare operational efficiency across different temporal segments.

#### Secondary Objectives

1. Support evidence-based operational planning.
2. Identify potential resource optimization opportunities.
3. Understand seasonal operational behavior.
4. Improve visibility into peak-pressure periods.
5. Provide an interactive analytical interface for decision-makers.


### 4. Data Ingestion and Understanding

The historical ferry ticket activity dataset was loaded into Python using Pandas.

The primary variables used in the analysis include:

- `_id` - Unique record identifier
- `Timestamp` - 15-minute interval timestamp
- `Sales Count` - Tickets sold during the interval
- `Redemption Count` - Tickets redeemed during the interval

The dataset was inspected to understand its structure, data types, dimensions, missing values, and analytical variables before beginning feature engineering.


### 5. Data Cleaning and Quality Checks

The dataset was prepared for analysis through a structured data-quality process.

The following activities were performed:

1. Dataset structure inspection.
2. Column validation.
3. Timestamp conversion to datetime format.
4. Numeric datatype validation.
5. Missing-value examination.
6. Duplicate-record checking.
7. Identification of unusual or irregular observations.
8. Preparation of the cleaned dataset for temporal analysis.

The original 15-minute resolution was preserved to maintain detailed operational information.


### 6. Temporal Feature Engineering

The timestamp was transformed into several analytical variables to enable detailed temporal analysis.

The following features were created:

- Year
- Month
- Month Name
- Day
- Hour
- Minute
- Day of Week
- Day of Week Number
- Weekend Indicator
- Day Type
- Time Band
- Season

These variables allow operational activity to be compared across different time periods, weekdays, weekends, seasons, and parts of the day.


### 7. Total Activity Load

A major operational feature was created by combining ticket sales and redemptions.

**Total Activity Load = Sales Count + Redemption Count**

This metric represents the overall ticket activity occurring within each 15-minute interval.

It provides a unified measure of operational activity and serves as the foundation for several downstream indicators.


### 8. Redemption Pressure Ratio

The project calculated a Redemption Pressure Ratio using:

**Redemption Pressure Ratio = Redemption Count / (Sales Count + 1)**

The additional constant prevents division-by-zero errors.

This indicator helps measure the relative relationship between ticket redemption and sales activity within each interval.


### 9. Rolling Operational Load Analysis

Rolling statistics were calculated to identify sustained operational patterns rather than relying only on individual observations.

The following rolling indicators were developed:

- Rolling 1-hour Load
- Rolling 4-hour Load
- Rolling 24-hour Load
- Rolling 24-hour Standard Deviation

These features help distinguish short-term activity spikes from sustained operational pressure.


### 10. Baseline Deviation and Activity Variability

The project developed baseline-based measures to identify how much activity differs from normal operating behavior.

The following indicators were created:

- Load Percentile
- Baseline Deviation
- Baseline Deviation Ratio
- Activity Z-Score

These measures help identify periods where operational activity is significantly higher or lower than expected.


### 11. Operational Load Index

An **Operational Load Index (OLI)** was developed as a normalized measure of interval-level operational pressure.

The OLI provides a standardized representation of operational activity and enables comparison between different intervals and periods.

This transforms raw activity counts into a more interpretable operational pressure indicator.


### 12. Capacity Utilization Proxy

Because the available dataset does not contain vessel-level physical capacity information, an **Activity-Based Capacity Utilization Proxy (%)** was used.

The utilization proxy provides an estimate of relative operational load and helps identify:

- High-utilization periods
- Low-utilization periods
- Potential capacity-pressure windows
- Relative operational efficiency

The metric is treated as a proxy rather than actual physical vessel occupancy.


### 13. Congestion Detection

Congestion-related indicators were developed to identify periods of elevated operational pressure.

The project includes:

- `Congestion_Flag`
- `Congestion_Group`
- `Congestion_Pressure_Index`
- `High_Load_Flag`

These indicators help identify intervals where activity exceeds normal operational conditions.

The Congestion Pressure Index provides a quantitative measure of operational pressure, while the flags support identification of high-pressure intervals.


### 14. Idle Capacity Detection

The project also identifies periods of low operational activity.

The following indicators were created:

- `Idle_Flag`
- `Idle_Group`

These indicators identify potential under-utilization periods and allow comparison between high-pressure and low-activity operating conditions.

This provides a balanced operational perspective by evaluating both congestion and under-utilization.


### 15. Anomaly Detection

Anomaly detection was incorporated to identify unusual activity patterns.

The analysis uses:

- Activity Z-Score
- Baseline Deviation
- Baseline Deviation Ratio
- Anomaly Flag

These features help distinguish unusual operational activity from normal variations and provide opportunities for further investigation.


### 16. Multi-Resolution Analysis

The project supports analysis at multiple temporal resolutions.

#### 15-Minute Analysis

Used to identify detailed short-duration operational patterns, congestion intervals, and idle periods.

#### Hourly Analysis

Used to identify peak operating hours and broader intraday activity patterns.

#### Daily Analysis

Used to examine day-level activity and support comparisons across weekdays, weekends, seasons, and years.

This multi-resolution approach enables both operational monitoring and strategic analysis.


### 17. Weekday vs Weekend Analysis

Operational activity was compared between weekdays and weekends.

The analysis uses the engineered Day Type and Weekend indicators to identify differences in operational load and utilization patterns.

This provides useful information for planning resources during different types of operating days.


### 18. Time-Band Efficiency Analysis

Activity was analyzed across different parts of the day using the Time Band feature.

The analysis compares:

- Morning
- Afternoon
- Evening

This helps identify periods of increased operational activity and potential opportunities for more efficient deployment.


### 19. Seasonal Efficiency Analysis

Seasonal patterns were analyzed to identify differences in operational activity and utilization.

The analysis evaluates:

- Average Activity Load
- Utilization
- Congestion
- Idle Percentage

This helps identify high-activity and low-activity seasons and supports seasonal operational planning.


### 20. Yearly Trend Analysis

Historical activity patterns were analyzed across years to identify long-term changes in:

- Activity Load
- Capacity Utilization Proxy
- Congestion Pressure
- Idle Conditions

This provides a long-term operational perspective and helps identify changes in ferry activity over the historical period.


### 21. Peak vs Idle Operational Comparison

A comparative analysis was performed between different operational states.

The comparison evaluates:

- Average Activity Load
- Average Utilization
- Average Congestion Pressure

This allows high-pressure periods to be compared with lower-activity operational periods and supports identification of potential efficiency gaps.


### 22. Peak Operating and Low-Activity Windows

Hourly activity patterns were analyzed to identify:

- Peak operating hour
- Lowest activity hour
- Highest-activity intervals
- Potential low-utilization windows

This provides direct operational information that can support time-based resource allocation and scheduling decisions.


### 23. Key Performance Indicators

The project consolidates the analysis into five primary KPIs.

#### KPI 1: Capacity Utilization Proxy (%)

Measures relative activity-based utilization.

#### KPI 2: Congestion Pressure Index

Measures the level of operational pressure associated with elevated activity.

#### KPI 3: Idle Capacity Percentage (%)

Measures the percentage of observations classified as idle.

#### KPI 4: Peak Strain Duration

Measures the longest sustained period of high operational load.

#### KPI 5: Operational Variability Score (%)

Measures the relative variability of operational activity.

Additional supporting indicators include:

- Congestion Rate
- High Load Rate
- Anomaly Rate
- Total Activity Load
- Sales Activity
- Redemption Activity


### 24. Business Intelligence and Operational Insights

The analytical framework transforms raw ticket activity into actionable operational information.

The project identifies:

- Peak operational periods
- Low-activity periods
- Congestion-prone intervals
- Idle-capacity periods
- Seasonal differences
- Operational variability
- Unusual activity patterns

This allows stakeholders to move beyond static ticket reporting toward data-informed operational monitoring.


### 25. Interactive Streamlit Dashboard

An interactive **Streamlit dashboard** was developed to present the analytical results in a user-friendly format.

The dashboard provides analytical views including:

- KPI Summary Cards
- Capacity Utilization Timeline
- Operational Activity Trends
- Congestion Analysis
- Idle Period Analysis
- Seasonal Efficiency Comparison
- Interactive filtering and visualization

The dashboard is designed as a decision-support interface that allows users to explore operational conditions more easily than through static notebook outputs.


### 26. Key Operational Recommendations

Based on the analytical framework, the following recommendations are proposed:

1. Prioritize operational monitoring during high-load and congestion-prone periods.

2. Use historical activity patterns to support time-based resource allocation.

3. Review consistently idle periods for opportunities to optimize ferry deployment and staffing.

4. Incorporate seasonal utilization patterns into operational scheduling decisions.

5. Monitor sustained high-load periods using Peak Strain Duration.

6. Investigate anomalous activity separately from normal operational conditions.

7. Use operational variability measurements to identify unstable or highly fluctuating periods.

8. Use the Capacity Utilization Proxy as an analytical planning indicator rather than a direct measurement of physical vessel occupancy.


### 27. Analytical Limitations

The available ticket activity dataset does not contain:

- Vessel-level physical capacity
- Vessel assignment information
- Actual passenger occupancy
- Staffing levels
- Fuel consumption
- Operating costs
- Trip-level cost information

Therefore, the project uses an **activity-based Capacity Utilization Proxy (%)** rather than claiming to measure actual physical vessel occupancy.

Similarly, direct monetary analysis of high-cost and low-utilization periods cannot be performed because operational cost information is not available.

These limitations are explicitly considered when interpreting the analytical results.


### 28. Overall Project Outcome

The project establishes a structured operational analytics framework that transforms raw ferry ticket activity into meaningful operational indicators.

The analytical pipeline can be summarized as:

**Raw Ticket Data**
    
↓

**Data Cleaning and Validation**

↓

**Temporal Feature Engineering**

↓

**Operational Feature Engineering**

↓

**Rolling Load and Baseline Analysis**

↓

**Capacity Utilization Proxy**

↓

**Congestion Detection**

↓

**Idle Capacity Detection**

↓

**Anomaly Detection**

↓

**KPI Development**

↓

**Operational Efficiency Analysis**

↓

**Business Insights and Recommendations**

↓

**Interactive Streamlit Dashboard**

The resulting system provides a comprehensive operational view of ferry activity and can support evidence-based planning and resource allocation.


### 29. Conclusion

The **Ferry Capacity Utilization & Operational Efficiency Analytics System** demonstrates how historical ferry ticket activity can be transformed into a practical operational intelligence solution.

The project combines data cleaning, temporal feature engineering, rolling statistics, utilization analysis, congestion detection, idle-capacity identification, anomaly detection, KPI development, comparative analysis, business insights, and interactive visualization.

The primary contribution of the project is its focus on **operational efficiency rather than simple demand reporting**.

The resulting framework provides transportation stakeholders with a structured method for identifying operational pressure, under-utilization, variability, and unusual activity patterns.

While the current dataset limits direct measurement of physical vessel occupancy and monetary operating costs, the activity-based analytical framework provides a strong foundation for operational monitoring and decision support.

Future improvements could incorporate vessel-level capacity, passenger occupancy, staffing information, operating costs, weather conditions, special events, and vessel scheduling data to enable more precise capacity and cost optimization.

Overall, the project demonstrates how data analytics can help transform historical transportation data into **actionable operational intelligence for more informed, efficient, and sustainable ferry planning.**
"""
